### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Diez15** [anilabhadatta/educative-viewer#10]
When using the latest release of educative-viewer or when cloning the latest version and running the python script manually, I get the following error:

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

The server correctly lists all the items, but clicking on any of them I get the above error. The python trace is:

`[2023-06-27 13:04:12,197] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2447, in wsgi_app
  File "flask\app.py", line 1952, in full_dispatch_request
  File "flask\app.py", line 1821, in handle_user_exception
  File "flask\_compat.py", line 39, in reraise
  File "flask\app.py", line 1950, in full_dispatch_request
  File "flask\app.py", line 1936, in dispatch_request
  File "educative-viewer.py", line 122, in topics
  File "flask\templating.py", line 137, in render_template
  File "flask\templating.py", line 120, in _render
  File "jinja2\environment.py", line 1090, in render
  File "jinja2\environment.py", line 832, in handle_exception
  File "jinja2\_compat.py", line 28, in reraise
  File "SNIP\templates\topics.html", line 39, in top-level template code
    {% include webpage %}
  File "jinja2\environment.py", line 832, in handle_exception
  File "jinja2\_compat.py", line 28, in reraise
  File "<unknown>", line 5, in template
jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag
192.168.100.43 - - [27/Jun/2023 13:04:12] "GET /favicon.ico HTTP/1.1" 500 -
192.168.100.43 - - [27/Jun/2023 13:05:43] "GET / HTTP/1.1" 200 -
`

I see that a similar issue was raised in the past and you marked it as fixed, but I am still getting the error. Can you provide any advice?

**Comment by Diez15** [comment]
@anilabhadatta can you please take a look and help me resolve this issue? Thank you!

**Comment by anilabhadatta** [comment]
@Diez15 may have some special characters that are causing issues during rendering.
Send me the Html file in a zip format here.
Also tell me if it is causing for each topics?
Video demonstration will be helpful

**Comment by sahibdhanjal** [comment]
@anilabhadatta - I'm facing a similar issue and was wondering if you had a solution for the same. I have cloned the repository and running it locally using a virtual environment. Unfortunately, it's happening with each and every page and I was wondering if you had a solution for the same?

[course.zip](https://github.com/anilabhadatta/educative-viewer/files/14290827/course.zip)

Thank You!

**Comment by anilabhadatta** [comment]
@sahibdhanjal checking

**Comment by anilabhadatta** [comment]
@sahibdhanjal the zip file you provided is having issues, you will need to re-scrape because i rescraped and it is working.
also use dark mode during scraping

**Comment by sahibdhanjal** [comment]
Ahh, got it, I'll re-scrape. Thanks a lot for looking into it, really appreciate it 👍🏻

**Comment by anilabhadatta** [comment]
@sahibdhanjal some updates were added as well. do pull

**Comment by sahibdhanjal** [comment]
Perfect, thanks man!

**Comment by iexa** [comment]
The simplest ffix for this bug is by changing the comment delimiters @ line 18-19 to this:
`app.jinja_env.comment_start_string = "{[(#"
app.jinja_env.comment_end_string = "#)]}"`

The code is a bit hard to understand though at first sight.
And the sidebar could be more transparent or automatically hidden so as not to obstruct the main view.

**Comment by anilabhadatta** [comment]
@iexa thanks i will update the jinja bug.
Also refer v3-dev branch.
New features were added and regarding the sidebar, will look a look for enhancement.
Also code is very unreadable at this moment, will fix it in coming days.

**Comment by iexa** [comment]
If you have the capacity you could try adding a light mode as well, the stuff I got are all light mode-scraped unfortunately :(

Would be great to use rar or zip files as well - I mean using a (list of) compressed rar / zip files, as the main data source the same as you do now but with folders / files. python's build in zipfile plus the 3rd party rarfile module would be fine. Reading the archive you can build up a list of links and when the actual html file would be read then it would be unpacked (to the system's temp folder - and read from there).

Or if you can make the code more humanely understandable I can add these features to your code, as I was thinking on making the same but using clean code principles as much as possible.

**Comment by anilabhadatta** [comment]
@iexa if you want you can make changes to the existing code.
Changes should be made to dev branch.
I am not getting much time to cleanup the code.
I will try to do it. But if you want to participate then I will leave it up to you to refactor the code and the features that you want to implement.

But do remember the zip features should be an optional one, the current architecture should remain stable.

**Comment by anilabhadatta** [comment]
@iexa currently i am busy fixing and implementing features in the scraper. I will see if i can make the code readable.

**Comment by sahibdhanjal** [comment]
> The simplest fix for this bug is by changing the comment delimiters @ line 18-19 to this:
> 
> ```python
> app.jinja_env.comment_start_string = "{[(#"
> app.jinja_env.comment_end_string = "#)]}"
> ```
> 
> Thanks for the effort. The code is a bit hard to understand though at first sight. And the sidebar could be more transparent or automatically hidden so as not to obstruct the main view.

Thanks @iexa , this worked for me 👍🏻

**Comment by anilabhadatta** [comment]
@iexa https://github.com/anilabhadatta/educative-viewer/tree/v4-dev
a lot of cleanup was done.
cleanup in main.py and topic_utils.py is left

**Comment by anilabhadatta** [comment]
@iexa refer to the latest commit on v4-dev branch, a lot of cleanup was done, should help you now understanding the code.
