### ISSUE TITLE
'course_directory' is not defined

### ISSUE THREAD

**Issue by deepakparamesh** [anilabhadatta/educative-viewer#17]
Facing an issue with this detail. Please let me know if anyone else have faced the same issue.

`NameError: name 'course_directory' is not defined
192.168.0.2 - - [13/May/2024 22:46:17] "GET / HTTP/1.1" 500 -
[2024-05-13 22:46:17,553] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "C:\Users\asdf\Personal_Projects\educative-viewer\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asdf\Personal_Projects\educative-viewer\env\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asdf\Personal_Projects\educative-viewer\env\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asdf\Personal_Projects\educative-viewer\env\Lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asdf\Personal_Projects\educative-viewer\educative-viewer.py", line 110, in topics
    topic_folders = natsort.natsorted(load_topics(course_directory))`

![image](https://github.com/anilabhadatta/educative-viewer/assets/12880320/a891febc-2d1a-44d0-a637-57a440dd1d5c)

**Comment by anilabhadatta** [comment]
@deepakparamesh use the latest educative-viewer, reclone to a new folder and go through the readme for setup

**Comment by anilabhadatta** [comment]
@deepakparamesh although older version should work, but i dont know which version are you using, so the last stable version 3 should work as per the setup method
